# Generated by Django 3.1.7 on 2021-03-10 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.IntegerField()),
                ('courier_type', models.CharField(max_length=4)),
                ('regions', models.TextField()),
                ('working_hours', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('weight', models.FloatField()),
                ('region', models.IntegerField()),
                ('delivery_hours', models.TextField()),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candy_shop.courier')),
            ],
        ),
    ]
