# Generated by Django 3.1.7 on 2021-03-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
