# Generated by Django 3.1.7 on 2021-03-16 07:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop', '0002_auto_20210310_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='assign_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 31, 20, 0), null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='complete_times',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='last_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 31, 20, 0), null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='orders',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 31, 20, 0), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 31, 20, 0), null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='candy_shop.courier'),
        ),
    ]
