# Generated by Django 3.1.7 on 2021-03-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop', '0004_auto_20210316_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_time',
        ),
        migrations.AlterField(
            model_name='courier',
            name='assign_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='last_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
