# Generated by Django 3.1.7 on 2021-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop', '0005_auto_20210317_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='assign_type',
            field=models.TextField(default=''),
        ),
    ]
