# Generated by Django 3.1.7 on 2021-03-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop', '0007_auto_20210320_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='assign_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='last_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
