# Generated by Django 3.1.7 on 2021-03-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candy_shop', '0009_courier_completed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='deliveries',
        ),
    ]
